<?php require_once __DIR__ . '/includes/header.phtml'; ?>
	<div class="row">
	    <div class="row">
	    	<div class="container">
	    		<h1>
	    			Acessar Sistema
	    		</h1>
	    	</div>
	    </div>
		<div class="container">
		    <?php if(isset($msg)): unset($_SESSION['msg']); ?>
				<div class="alert alert-success">
					<?=$msg;?>
				</div>
		    <?php endif;?>
			<form method="post" action="/?p=login">
			  <div class="form-group">
			    <label for="exampleInputEmail1">Login</label>
			    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Login" name="login">
			  </div>
			 <div class="form-group">
			    <label for="exampleInputEmail1">Senha</label>
			    <input type="password" class="form-control" id="exampleInputEmail1" placeholder="Senha" name="password">
			  </div>
 
			  <button type="submit" class="btn btn-default">Acessar</button>
			</form>
		</div>
	</div>
</body>
<?php require_once __DIR__ . '/includes/footer.phtml'; ?>