<?php require TEMPLATES . '/includes/header.phtml';?>

<div class="row">
    <?php foreach ($products as $key => $product): ?>
        <div class="card" style="width: 22rem;">
            <img class="card-img-top" alt="Card image cap" src="https://placeimg.com/640/280/any" class="img-fluid">
            <div class="card-body">
                <h5 class="card-title"><?=$product->name;?></h2>
                <p class="card-text">
                <?=$product->description;?>
                </p>
                <h4>R$ <?=number_format($product->price, 2, ',', '.');?></h4>
                <a href="<?=HOME;?>/products/view/<?=$product->slug;?>" class="btn btn-success">Ver Mais</a>
            </div>
        </div>
        <?php if (($key + 1) % 3 == 0): ?> </div><div class="row"> <?php endif;?>
    <?php endforeach;?>
</div>

<?php require TEMPLATES . '/includes/footer.phtml';?>

