<?php require VIEWS_FOLDER . "includes/header.phtml"; ?>

        <section class="content">

           <div class="posts">
           
            <article class="post">
                <img src="https://placeimg.com/640/280/any">
                <h2>Titulo da Postagem</h2>
                <p>
                    Lorem, ipsum dolor sit 
                    amet consectetur adipisicing 
                    elit. Perspiciatis possimus 
                    deserunt sed maiores autem 
                    pariatur ex at fugiat, dolores 
                    provident!
                </p>
                <a href="#">Leia mais...</a>
             </article>

            <article class="post">
                <img src="https://placeimg.com/640/280/any">
                <h2>Titulo da Postagem</h2>
                <p>
                    Lorem, ipsum dolor sit
                    amet consectetur adipisicing
                    elit. Perspiciatis possimus
                    deserunt sed maiores autem
                    pariatur ex at fugiat, dolores
                    provident!
                </p>
                <a href="#">Leia mais...</a>
            </article>

            <article class="post">
                <img src="https://placeimg.com/640/280/any">
                <h2>Titulo da Postagem</h2>
                <p>
                    Lorem, ipsum dolor sit
                    amet consectetur adipisicing
                    elit. Perspiciatis possimus
                    deserunt sed maiores autem
                    pariatur ex at fugiat, dolores
                    provident!
                </p>
                <a href="#">Leia mais...</a>
            </article>

            <article class="post">
                <img src="https://placeimg.com/640/280/any">
                <h2>Titulo da Postagem</h2>
                <p>
                    Lorem, ipsum dolor sit
                    amet consectetur adipisicing
                    elit. Perspiciatis possimus
                    deserunt sed maiores autem
                    pariatur ex at fugiat, dolores
                    provident!
                </p>
                <a href="#">Leia mais...</a>
            </article>
           
            </div>

           <aside class="sidebar">
           
            <div class="sidebar-item">
                <h3 class="sidebar-item-title">
                  Patrocinado
                </h3>

                <div class="sidebar-item-content">
                   <img src="http://www.onestepads.com/storage/app/logos/1502351186One%20Step%20Ads%20380x260%20wo%20LOGO%20-%201.png"> 
                </div>
            </div>

            <div class="sidebar-item">
                <h3 class="sidebar-item-title">
                    Patrocinado
                </h3>
            
                <div class="sidebar-item-content">
                    <img
                        src="http://www.onestepads.com/storage/app/logos/1502351186One%20Step%20Ads%20380x260%20wo%20LOGO%20-%201.png">
                </div>
            </div>

            <div class="sidebar-item">
                <h3 class="sidebar-item-title">
                    Patrocinado
                </h3>
            
                <div class="sidebar-item-content">
                    <img
                        src="http://www.onestepads.com/storage/app/logos/1502351186One%20Step%20Ads%20380x260%20wo%20LOGO%20-%201.png">
                </div>
            </div>

           </aside>

        </section>

<?php require VIEWS_FOLDER . "includes/footer.phtml" ?>