<?php require VIEWS_PATH . '/includes/header.phtml';?>
<div class="container">
	<h1>Carrinho de Compras</h1>
	<hr>
	<table class="table">
		<thead>
			<tr>
				<td>#</td>
				<td>Produto</td>
				<td>Valor</td>
			</tr>
		</thead>
		<tbody>
            <?php foreach($products as $p):?>
                <tr>
                    <td>#</td>
                    <td><?=$p['name'];?></td>
                    <td>
                        R$ <?=number_format($p['price'], 2, ',', '.');?> |
                        <a href="<?=HOME;?>/cart/remove/<?=$p['slug'];?>">REMOVER</a>
                    </td>
                </tr>
            <?php endforeach;?>
            <tr>
                <td></td>
                <td>Total: </td>
                <td>R$ <?=number_format($total, 2, ',', '.');?></td>
            </tr>
		</tbody>
	</table>
</div>
<?php require VIEWS_PATH . '/includes/footer.phtml';?>
