<?php require TEMPLATES . '/includes/header.phtml';?>

<h1>Produtos</h1>
<hr>

<div class="row products">
    <?php foreach($products as $key => $product):?>
        <div class="col-md-4">
            

            <img src="https://placeimg.com/640/280/any" alt="" class="img-fluid">
            <h2><?=$product->name;?></h2>

            <span>R$ <?=number_format($product->price, 2, ',', '.');?></span>

            <p>
                <?=$product->description;?>
            </p>

            <a href="<?=HOME . '/products/view/' . $product->slug;?>" class="btn btn-success">
                Comprar
            </a>
        </div>
       
        <?php if(($key + 1) % 3 == 0):?></div><div class="row products"> <?php endif;?>

    <?php endforeach; ?>
</div>

<?php require TEMPLATES . '/includes/footer.phtml';?>
