<?php require TEMPLATES . '/includes/header.phtml';?>

<h1>Produtos</h1>
<hr>
<div class="row">
    <?php foreach($products as $product):?>
        <div class="col-md-4">
            

            <img src="https://placeimg.com/640/280/any" alt="" class="img-fluid">
            <h2><?=$product['name'];?></h2>

            <span>R$ <?=number_format($product['price'], 2, ',', '.');?></span>
        </div>
    <?php endforeach; ?>
</div

<?php require TEMPLATES . '/includes/footer.phtml';?>
