<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <title>Upload</title>
</head>
<body>
    <div class="container">
        <h1>Upload de Arquivo!!!!</h1>
        <hr>
        <form action="" method="post" class="form-control" enctype="multipart/form-data">
            <div class="form-group">
                <input type="file" name="upload">
            </div>
            <button type="submit" class="btn btn-lg btn-success">
                Salvar Arquivo
            </button>
        </form>
    </div>
</body>
</html>