<?php require VIEWS_PATH . 'includes/header.phtml'; ?>
<div class="container">
	<div class="col">
		<h1>Usuários</h1>
		<hr>
	</div>
	<div class="col">
		<table class="table table-striped">
			<thead>
			<tr>
				<th>Nome</th>
				<th>Email</th>
				<th>Telefone</th>
				<th>Criado em</th>
				<th>Ações</th>
			</tr>
			</thead>
			<tbody>
			<?php foreach(select($conn, 'usuarios') as $u): ?>
				<tr>
					<td><?=$u['nome'];?></td>
					<td><?=$u['email'];?></td>
					<td><?=$u['telefone'];?></td>
					<td><?=date('d/m/Y', strtotime($u['criado_em']));?></td>
					<td>
						<a href="<?=HOME;?>/edit/<?=$u['id'];?>" class="btn btn-primary">
							Editar
						</a>
						<a href="<?=HOME;?>/delete/<?=$u['id'];?>" class="btn btn-danger">
							Remover
						</a>
					</td>
				</tr>
			<?php endforeach;?>
			</tbody>
		</table>
	</div>
</div>
<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>
