<?php require APP_VIEWS . 'store/includes/header.phtml'; ?>
    <div class="container">
        <h1>Formação PHP</h1>
        <hr>
        <div class="col-md-12">
            <?php foreach($this->products as $p): ?>
                <div class="col-md-4">
                    <img src="http://placehold.it/350x150" alt="">
                    <h2>
                        <a href="/product/view/<?=$p['slug'];?>"><?=$p['name'];?></a>
                    </h2>
                    <p>R$ <?=number_format($p['price'], 2, ',', '.');?></p>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php require APP_VIEWS . 'store/includes/footer.phtml'; ?>
