<?php require APP_VIEWS . 'store/includes/header.phtml'; ?>
    <div class="container">
        <h1>Formação PHP</h1>
        <hr>
        <div class="col-md-12">
                <div class="col-md-6">
                    <img src="http://placehold.it/350x150" alt="">
                </div>
                <div class="col-md-6">
                    <h2>
                        <a href="/product/view/<?=$this->product['slug'];?>"><?=$this->product['name'];?></a>
                    </h2>
                    <p>R$ <?=number_format($this->product['price'], 2, ',', '.');?></p>
                    <a href="" class="btn btn-success btn-lg">
                        Comprar
                    </a>
                </div>
        </div>
    </div>
<?php require APP_VIEWS . 'store/includes/footer.phtml'; ?>
