  <?php require __DIR__ . '/includes/header.phtml';?>  
  
  <section class="content">
        <div class="posts">
            <article class="post">
                <img src="https://placeimg.com/640/250/any">
                <h2>Titulo da Postagem</h2>
                <p>
                    Lorem ipsum dolor sit 
                    amet consectetur adipisicing 
                    elit. Molestias, deleniti? 
                    Lorem ipsum dolor sit
                    amet consectetur adipisicing
                    elit. Molestias, deleniti?
                    Lorem ipsum dolor sit
                    amet consectetur adipisicing
                    elit. Molestias, deleniti?
                </p>
            </article>
            
            <article class="post">
                <img src="https://placeimg.com/640/250/any">
                <h2>Titulo da Postagem</h2>
                <p>
                    Lorem ipsum dolor sit
                    amet consectetur adipisicing
                    elit. Molestias, deleniti?
                    Lorem ipsum dolor sit
                    amet consectetur adipisicing
                    elit. Molestias, deleniti?
                    Lorem ipsum dolor sit
                    amet consectetur adipisicing
                    elit. Molestias, deleniti?
                </p>
            </article>
            
            <article class="post">
                <img src="https://placeimg.com/640/250/any">
                <h2>Titulo da Postagem</h2>
                <p>
                    Lorem ipsum dolor sit
                    amet consectetur adipisicing
                    elit. Molestias, deleniti?
                    Lorem ipsum dolor sit
                    amet consectetur adipisicing
                    elit. Molestias, deleniti?
                    Lorem ipsum dolor sit
                    amet consectetur adipisicing
                    elit. Molestias, deleniti?
                </p>
            </article>
            
            <article class="post">
                <img src="https://placeimg.com/640/250/any">
                <h2>Titulo da Postagem</h2>
                <p>
                    Lorem ipsum dolor sit
                    amet consectetur adipisicing
                    elit. Molestias, deleniti?
                    Lorem ipsum dolor sit
                    amet consectetur adipisicing
                    elit. Molestias, deleniti?
                    Lorem ipsum dolor sit
                    amet consectetur adipisicing
                    elit. Molestias, deleniti?
                </p>
            </article>
        </div>
        
        <aside class="sidebar">
            
            <div class="sidebar-item">
                <h4 class="sidebar-item-title">
                    Bloco Lateral
                </h4>
                
                <div class="sidebar-item-content">
                    <p>
                        Lorem ipsum dolor sit
                        amet consectetur adipisicing
                        elit. Eveniet, natus.
                    </p>
                </div>
            </div>
            
            <div class="sidebar-item">
                <h4 class="sidebar-item-title">
                    Bloco Lateral
                </h4>
                
                <div class="sidebar-item-content">
                    <p>
                        <img src="https://placeimg.com/280/250/any">
                    </p>
                </div>
            </div>
            
            <div class="sidebar-item">
                <h4 class="sidebar-item-title">
                    Bloco Lateral
                </h4>
                
                <div class="sidebar-item-content">
                    <p>
                        Lorem ipsum dolor sit
                        amet consectetur adipisicing
                        elit. Eveniet, natus.
                    </p>
                </div>
            </div>
            
        </aside>
    </section>
    
  <?php require __DIR__ . '/includes/footer.phtml';?>  