<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Loja Formação PHP</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
<div class="row">
    <div class="container" style="padding: 10px 0px;">
        <a href="<?=HOME;?>/cart/index" class="btn btn-sm btn-primary float-right">
            CART
            <?php if($productsCount = (new \Cart\Cart())->showProducts()):?>
                | <?=count($productsCount);?>
            <?php endif;?>
        </a>
    </div>
</div>

