<h1>Criar Usuário</h1>

<form action="/salvar" method="post">
    <p>
        <label>Nome Completo</label> <br>
        <input type="text" name="name">
    </p>
    
    <p>
        <label>E-mail</label> <br>
        <input type="email" name="email">
    </p>
    <p>
        <label>Senha</label> <br>
        <input type="password" name="password">
    </p>
    <button type="submit">Cadastrar</button>
</form>