<?php require TEMPLATES . '/includes/header.phtml';?>

<h1>Atualizar Usuário</h1>

<form action="/atualizar/<?=$contact['id'];?>" method="post">
    <div class="form-group">
        <label>Nome Completo</label>
        <input type="text" name="name" class="form-control" value="<?=$contact['name'];?>">
    </div>
    
    <div class="form-group">
        <label>E-mail</label> <br>
        <input type="email" name="email"  class="form-control" value="<?=$contact['email'];?>">
    </div>
    <div class="form-group">
        <label>Senha</label> <br>
        <input type="password" name="password" class="form-control">
    </div>
    <button type="submit" class="btn btn-lg btn-success">Atualizar</button>
</form>
<?php require TEMPLATES . '/includes/footer.phtml';?>