<?php require TEMPLATES . '/includes/header.phtml';?>

<div class="row" style="padding-top: 10px;">
    <div class="col-md-12">
    <h1 class="float-left">Home</h1>
    <a href="/criar" class="btn btn-lg btn-success float-right">Criar Contato</a>
    </div>
</div>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Criado Em</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($users as $user): ?> 
        <tr>
            <td><?=$user['id'];?></td>
            <td><?=$user['name'];?></td>
            <td><?=$user['created_at'];?></td>
            <td>
                <a href="/editar/<?=$user['id'];?>" class="btn btn-sm btn-warning">EDITAR</a>
                <a href="/remover/<?=$user['id'];?>" class="btn btn-sm btn-danger">REMOVER</a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php require TEMPLATES . '/includes/footer.phtml';?>
