<?php require VIEWS_PATH . 'includes/header.phtml';?>
	<!-- Main jumbotron for a primary marketing message or call to action -->
	<div class="jumbotron"></div>
	<div class="container">
	<!-- Example row of columns -->
	<div class="row">
		<div class="col-md-12">
			<?php require VIEWS_PATH . 'includes/messages.phtml';?>
		</div>
		<div class="col-md-6" style="border-right: 1px solid #CCC;">
			<form action="<?=HOME;?>cadastro/novo" method="POST">
				<h2>Cadastrar</h2>
				<hr>
				<div class="form-group">
					<label for="exampleInputEmail1">Nome(*)</label>
					<input type="text" class="form-control" placeholder="Nome" name="name" <?php if(isset($_POST['name'])):?> value="<?=$_POST['name'];?>" <?php endif;?>>
				</div>

				<div class="form-group">
					<label for="exampleInputEmail1">Email(*)</label>
					<input type="email" class="form-control" placeholder="Email" name="email" <?php if(isset($_POST['email'])):?> value="<?=$_POST['email'];?>" <?php endif;?>>
				</div>

				<div class="form-group">
					<label for="exampleInputPassword1">Password(*)</label>
					<input type="password" class="form-control" placeholder="Password" name="password">
				</div>

				<button type="submit" class="btn btn-success">Cadastrar & Continuar</button>
			</form>
		</div>
		<div class="col-md-6">
			<h2>Autenticar</h2>
			<hr>
			<form action="<?=HOME;?>cadastro/login" method="POST">
				<div class="form-group">
					<label for="exampleInputEmail1">Email(*)</label>
					<input type="email" class="form-control" placeholder="Email" name="email" <?php if(isset($_POST['email'])):?> value="<?=$_POST['email'];?>" <?php endif;?>>
				</div>

				<div class="form-group">
					<label for="exampleInputPassword1">Password(*)</label>
					<input type="password" class="form-control" placeholder="Password" name="password">
				</div>

				<button type="submit" class="btn btn-success">Logar & Continuar</button>
			</form>
		</div>
	</div>
<?php require VIEWS_PATH . 'includes/footer.phtml';?>