<?php require __DIR__ . '/includes/header.phtml';?>
	<div class="jumbotron">
		<div class="container">
			<h1>Produto</h1>
		</div>
	</div>
	<div class="col-md-12">
		<?php require __DIR__ . '/includes/messages.phtml';?>
	</div>
	<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-12">
			<?php if($this->products): ?>
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Produtos</th>
                            <th></th>
                            <th></th>
                            <th class="text-center">Preço</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
					<?php foreach($this->products['products'] as $key => $product):?>
                        <tr>
                            <td>
                                <div class="media">
                                    <a class="thumbnail pull-left" href="#">
                                        <img src="http://via.placeholder.com/350x150?text=CODE" alt="" class="img-responsive">
                                    </a>
                                    <div class="media-body">
                                        <h5 class="media-heading">
                                            <a href="<?=HOME;?>produto/<?=$product['slug'];?>"><?=$product['name'];?></a>
                                        </h5>
                                    </div>
                                </div>
                            </td>
                            <td></td>
                            <td></td>
                            <td class="col-sm-2 col-md-2 text-center"><strong>R$ <?=number_format($product['price'], 2, ',', '.');?></strong></td>
                            <td class="col-sm-2 col-md-2">
                                <a href="/cart/remove/<?=$product['slug'];?>" class="btn btn-danger">
                                    <span class="fa fa-close"></span>
                                </a></td>
                        </tr>
					<?php endforeach;?>

                    <tr>
                        <td>   </td>
                        <td>   </td>
                        <td>   </td>
                        <td><h3>Total</h3></td>
                        <td class="text-right"><h3><strong>R$ <?=number_format($this->products['total'], 2, ',', '.');?></strong></h3></td>
                    </tr>
                    <tr>
                        <td>   </td>
                        <td>   </td>
                        <td>   </td>
                        <td>
                            <a href="<?=HOME;?>" class="btn btn-danger">
                                <span class="glyphicon glyphicon-shopping-cart"></span> Continuar Comprando
                            </a></td>
                        <td>
                            <a  href="<?=HOME;?>cadastro"  class="btn btn-success">
                                Concluir Compra <span class="glyphicon glyphicon-play"></span>
                            </a>
                        </td>
                    </tr>
                    </tbody>
                </table>
			<?php else: ?>
                <div class="alert alert-warning">
                    Nenhum produto no carrinho
                    <a href="<?=HOME;?>" class="pull-right">Voltar</a>
                </div>
			<?php endif; ?>
        </div>
    </div>
<?php require __DIR__ . '/includes/footer.phtml';?>