<?php require VIEWS_PATH . '/includes/header.phtml';?>
<div class="container">
	<div class="row">
		<?php foreach($this->products as $product):?>
			<div class="col-md-4">
				<img src="http://via.placeholder.com/350x150?text=CODE" alt="" class="img-responsive">
				<h2>
					<a href="<?=HOME;?>produto/<?=$product['slug'];?>">
						<?=$product['name'];?>
					</a>
				</h2>
				<span>R$ <?=number_format($product['price'], 2, ',', '.');?></span>
			</div>
		<?php endforeach;?>
	</div>
</div>
<?php require VIEWS_PATH . '/includes/footer.phtml';?>