<?php require __DIR__ . '/includes/header.phtml';?>
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
	<div class="container">
		<h1>Produto</h1>
	</div>
</div>
<div class="col-md-12">
  <?php require __DIR__ . '/includes/messages.phtml';?>
</div>
<div class="col-md-12">
<!-- Example row of columns -->
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-12">
            <?php if($this->products): ?>
                <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Product</th>
                        <th> </th>
                        <th> </th>
                        <th class="text-center">Price</th>

                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->products['products'] as $key => $product):?>
                    <tr>
                        <td>
                        <div class="media">
                            <a class="thumbnail pull-left" href="#"> 
                            <?php if(file_exists($thumb = "/assets/img/uploads/products/" . $this->product['thumb'])):?>
                                  <img src="<?=$thumb;?>" alt="" width="72px" style="margin-right: 10px;">
                            <?php else:?>
                              <img src="/assets/img/img.jpg" alt="" class="img-responsive" width="72px">
                            <?php endif;?> 
                            </a>
                            <div class="media-body">
                                <h4 class="media-heading"><a href="#"><?=$product['name'];?></a></h4>
                                <h5 class="media-heading"> by <a href="#">Body Builder</a></h5>
                            </div>
                        </div></td>
  <td></td>
                        <td></td>
                        <td class="col-sm-2 col-md-2 text-center"><strong>R$ <?=number_format($product['price'], 2, ',', '.');?></strong></td>
                        <td class="col-sm-2 col-md-2">
                        <a href="/cart/remove/<?=$product['slug'];?>" type="button" class="btn btn-danger">
                            <span class="fa fa-close"></span>
                        </a></td>
                    </tr>
                    <?php endforeach;?>
            
                    <tr>
                        <td>   </td>
                        <td>   </td>
                        <td>   </td>
                        <td><h3>Total</h3></td>
                        <td class="text-right"><h3><strong>R$ <?=number_format($this->products['total'], 2, ',', '.');?></strong></h3></td>
                    </tr>
                    <tr>
                        <td>   </td>
                        <td>   </td>
                        <td>   </td>
                        <td>
                        <a href="/" class="btn btn-default">
                            <span class="glyphicon glyphicon-shopping-cart"></span> Continuar Comprando
                        </a></td>
                        <td>
                        <a  href="/checkout"  class="btn btn-success">
                            Pagar Com PagSeguro <span class="glyphicon glyphicon-play"></span>
                        </a></td>
                    </tr>
                </tbody>
            </table>
        <?php else: ?>
            <div class="alert alert-warning">
                Nenhum produto no carrinho
                <a href="/" class="pull-right">Voltar</a>
            </div>
        <?php endif; ?>
        </div>
    </div>
</div>
<?php require __DIR__ . '/includes/footer.phtml';?>