<html>
    
    <head>
        <meta charset="UTF-8">
        <title>Blog</title>
        <link rel="stylesheet" href="assets/css/style.css">   
    </head>

    <body>
        <header class="header">
            <nav class="menu">
                <ul class="list">
                    <li class="list-item"><a href="#">Home</a></li>
                    <li class="list-item"><a href="#">Sobre</a></li>
                    <li class="list-item"><a href="#">Categorias</a></li>
                    <li class="list-item"><a href="#">Serviços</a></li>
                    <li class="list-item"><a href="#">Contato</a></li>
                </ul>
            </nav>
        </header>