<?php $msg = \Code\Service\SessionService::getFlash('warning'); if($msg): ?>
	<div class="alert alert-warning">
		<?=$msg;?>
	</div>
<?php endif;?>

<?php $msg = \Code\Service\SessionService::getFlash('error'); if($msg): ?>
	<div class="alert alert-danger">
		<?=$msg;?>
	</div>
<?php endif;?>

<?php $msg = \Code\Service\SessionService::getFlash('success'); if($msg): ?>
	<div class="alert alert-success">
		<?=$msg;?>
	</div>
<?php endif;?>